### ISSUE TITLE
Django Dashboard Dashkit PRO - manage.py collectstatic Failed

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-dashkit-v3#1]
Command **python manage.py collectstatic** failed to post-process several CSS files:
- assets / css / **app.css** - [Django Dashboard Dashkit](https://appseed.us/admin-dashboards/django-dashboard-dashkit-pro) CSS dependencies
- assets / css / **dashboard.css** - [Django Dashboard Dashkit](https://appseed.us/admin-dashboards/django-dashboard-dashkit-pro) App CSS 
- assets / css / **icons.min.css** - [Django Dashboard Dashkit](https://appseed.us/admin-dashboards/django-dashboard-dashkit-pro) CSS dependencies

Blocks that generate the errors contain relatives paths for fonts and images:

```css
/* Defined in dashboard.css */
.peity-card {
  background-image: url(../images/bg/dashboard/chart-bg.svg);
}

/* Defined in dashboard.css */
.sorting {
  background-image: url(../images/icons/datatable/sort_both.png);
}
```

Explanation: Looks like [WhiteNoise](http://whitenoise.evans.io/en/stable/) have issues with relative paths
[Django Dashboard Dashkit PRO](https://appseed.us/admin-dashboards/django-dashboard-dashkit-pro) version - v1.0.0
